name: example
description: example SQFEntity Project

version: 2.2.0+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqfentity: ^2.3.0+5
  sqfentity_gen: ^2.3.0+4
  path_provider: ^2.0.15
  http: ^0.13.6


dependency_overrides:
  sqfentity: 
    path: ../../sqfentity
  sqfentity_gen: 
    path: ../../sqfentity_gen      

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0

  cupertino_icons: ^1.0.5

flutter:

  uses-material-design: true
